データソースをサウナイキタイから変更する
asaka2-alb/smart-sauna-map-back pull request #28
Opened 2023-05-04 08:06 UTC by siida36

## 概要

2023-05-05 02:19 UTC, taisei-watanabe reviewed
下記のコマンドが動作することを確認しました。

```console
❯ curl -X POST -H "Content-type: application/json"  -d '{"query": "御殿場"}' http://127.0.0.1:5000/geocode
❯ curl -X POST -H "Content-type: application/json"  -d '{"keyword": "御殿場"}'  http://127.0.0.1:5000/search_sauna
```

あとは `GoogleMapScraper` or `GoogleMapSeacher` が正式にできてからのレビューになりますかね。

2023-05-05 02:19 UTC, taisei-watanabe commented on src/smart_sauna_map/scraper/sauna_ikitai_scraper.py
> +class SaunaIkitaiScraper(AbstractScraper):
GoogleMap だとスクレイピングしているわけではないので `SaunaIkitaiSearcher`, `AbstractSearcher`, `GoogleMapSearcher` で良いような気がします。

2023-05-05 02:19 UTC, taisei-watanabe commented on src/smart_sauna_map/scraper/sauna_ikitai_scraper.py
> +        return ikitai
せっかくモジュールに分けていますし、これらのメソッドは `self` を利用する必要がないので、このモジュールに関数として置いておいて良いような気がしました。

2023-05-05 02:19 UTC, taisei-watanabe commented on src/smart_sauna_map/scraper/abstract_scraper.py
> +from abc import ABC, abstractmethod
ディレクトリ名は `searchers` で良いような気がします。

2023-05-05 02:19 UTC, taisei-watanabe commented on src/smart_sauna_map/room.py
`room.py`, `sauna.py` は `data_models` のようなディレクトリを作って、そこに入れましょうか。

2023-05-05 02:19 UTC, taisei-watanabe commented on src/smart_sauna_map/api.py
> +    sauna = _search_sauna(keyword=keyword, scraper=GoogleMapScraper())
ここ良いですね。
ありがとうございます！

2023-05-05 02:19 UTC, taisei-watanabe commented on src/smart_sauna_map/api.py
>          >>> curl -X POST -H "Content-type: application/json"  -d '{"keyword": "御殿場",
細かいですが、不要そうなのでここのコンマは外しましょうか。

```diff
- >>> curl -X POST -H "Content-type: application/json" -d '{"keyword": "御殿場",
+ >>> curl -X POST -H "Content-type: application/json" -d '{"keyword": "御殿場"
```

2023-05-05 07:22 UTC, siida36 commented on src/smart_sauna_map/scraper/sauna_ikitai_scraper.py
> +class SaunaIkitaiScraper(AbstractScraper):
ありがとうございます！Scraper -> Searcherのリネームを 3f9378e で実施しました。

2023-05-05 07:22 UTC, siida36 commented on src/smart_sauna_map/scraper/abstract_scraper.py
> +from abc import ABC, abstractmethod
3f9378e で対応しました！

2023-05-05 07:37 UTC, siida36 commented on src/smart_sauna_map/scraper/sauna_ikitai_scraper.py
> +        return ikitai
9491b86 で対応しました！

2023-05-05 07:46 UTC, siida36 commented on src/smart_sauna_map/room.py
4b82aa3 で対応しました！

2023-05-05 07:50 UTC, siida36 commented on src/smart_sauna_map/api.py
>          >>> curl -X POST -H "Content-type: application/json"  -d '{"keyword": "御殿場",
1c6730d で対応しました！

2023-05-05 07:52 UTC, siida36 commented
@taisei-watanabe 
レビューありがとうございます！こちら一通り対応しましたmm
https://github.com/asaka2-alb/smart-sauna-map-back/pull/28#pullrequestreview-1414106202

2023-05-06 02:07 UTC, taisei-watanabe commented on src/smart_sauna_map/scraper/abstract_scraper.py
> +from abc import ABC, abstractmethod
あんまりこだわりすぎてもあれなんですけど searcher`s` ですかね

2023-05-06 02:13 UTC, taisei-watanabe requested changes
Render で [PR がうまくデプロイされていない](https://dashboard.render.com/web/srv-ch9meupmbg5e7q0aefdg)ようなので確認をお願いします。

以下のようなエラーが送出されていますね。

```py
May 6 11:10:40 AM      mod = importlib.import_module(module)
May 6 11:10:40 AM    File "/opt/render/project/python/Python-3.9.13/lib/python3.9/importlib/__init__.py", line 127, in import_module
May 6 11:10:40 AM      return _bootstrap._gcd_import(name[level:], package, level)
May 6 11:10:40 AM    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
May 6 11:10:40 AM    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
May 6 11:10:40 AM    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
May 6 11:10:40 AM    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
May 6 11:10:40 AM    File "<frozen importlib._bootstrap_external>", line 850, in exec_module
May 6 11:10:40 AM    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
May 6 11:10:40 AM    File "/opt/render/project/src/app.py", line 2, in <module>
May 6 11:10:40 AM      from smart_sauna_map.api import app
May 6 11:10:40 AM  ModuleNotFoundError: No module named 'smart_sauna_map'
```

2023-05-06 02:13 UTC, taisei-watanabe commented on src/smart_sauna_map/searcher/sauna_ikitai_searcher.py
> +        return [sauna(s) for s in soup.find_all(class_="p-saunaItem")]
これらのメソッドも `self` を利用しているわけではないので、外してしまって良いような気がします。

2023-05-06 02:22 UTC, taisei-watanabe commented
Render のデプロイ失敗の件, Build コマンドが以下のようになっているので 

<img width="675" alt="Screen Shot 2023-05-06 at 11 20 52" src="https://user-images.githubusercontent.com/63327908/236593530-88142e4a-ad99-4816-8287-8d151a258453.png">

```console
pip install .
```

に変えてあげてば正しく動作するような気がしております。

2023-05-06 02:24 UTC, taisei-watanabe commented
これ表示間違っていますね。。一度 workflows にある test.yml ファイルを削除するなどしないとリセットされないんでしょうか。

<img width="567" alt="Screen Shot 2023-05-06 at 11 24 06" src="https://user-images.githubusercontent.com/63327908/236593668-d72bc86d-2d49-4e5c-8f2d-55886416f567.png">

2023-05-06 03:05 UTC, siida36 commented on src/smart_sauna_map/scraper/abstract_scraper.py
> +from abc import ABC, abstractmethod
e27b854 で対応しました！

2023-05-06 03:07 UTC, siida36 commented on src/smart_sauna_map/api.py
> +        else eval(request.get_json()["searcher"] + "()")
[75cee27](https://github.com/asaka2-alb/smart-sauna-map-back/pull/28/commits/75cee27351c74cb13f2858a73551896dfc630292) で対応済み

2023-05-06 03:59 UTC, siida36 commented
Renderのデプロイ失敗の件はビルドコマンドを次のように変更して対処しました。
`pip install poetry -U; poetry install`

`pip install poetry -U` を追加した理由は下記の通りです。
https://stackoverflow.com/questions/73876790/poetry-configuration-is-invalid-additional-properties-are-not-allowed-group

2023-05-06 04:01 UTC, siida36 commented
> これ表示間違っていますね。。一度 workflows にある test.yml ファイルを削除するなどしないとリセットされないんでしょうか。

こちら何が問題になっているんでしたっけ？？

2023-05-06 04:08 UTC, siida36 commented on src/smart_sauna_map/searcher/sauna_ikitai_searcher.py
> +        return [sauna(s) for s in soup.find_all(class_="p-saunaItem")]
ec77734 で対応しました！

2023-05-06 04:08 UTC, siida36 commented
@taisei-watanabe 
一通りコメ返ししたので確認お願いしますmm

2023-05-07 01:09 UTC, taisei-watanabe approved these changes

2023-05-07 01:09 UTC, merged