[feature/#2-fix-notfound] 緯度軽度を取得できなかった場合のエラーハンドリングを追加
asaka2-alb/smart-sauna-map-back pull request #7
Opened 2022-05-10 01:33 UTC by siida36

## 概要

`get_latlng.py` のテストを書いて、さらに #2 に対処しました。

## レビューしてほしいポイント

- テストの妥当性
- エラー処理の妥当性

2022-05-13 00:36 UTC, taisei-watanabe commented on src/smart_sauna_map/get_latlng.py
> +    if len(res_dict["results"]) != 1:
以下のようなコメントが追加されていると適切なエラーを実装する際の対応がわかりやすくなると思います。:smile:

```py
    # TODO: We will remove this block, if an appropriate error handling will be implemented.
    if len(res_dict["results"]) != 1:
```

2022-05-16 01:03 UTC, siida36 commented on src/smart_sauna_map/get_latlng.py
> +    if len(res_dict["results"]) != 1:
ありがとうございます！コメント文はそのままいただきました bbdd016

2022-05-16 01:04 UTC, siida36 commented
ステータスコードを返すように修正しました。 [f61201a](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/f61201a3960e93bc48d911fd1a350e441591893f)

2022-05-23 01:01 UTC, siida36 commented
TODO: errorhandler デコレータを使ってエラー処理を書き直す

```
from flask import render_template

@app.errorhandler(404)
def page_not_found(e):
    # note that we set the 404 status explicitly
    return render_template('404.html'), 404
```

https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/errorhandling.html#custom-error-pages

2022-05-25 01:21 UTC, siida36 commented
[errorhandlerデコレータ](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7#issuecomment-1134047984)の修正対応しました。

- case1
    - 入力
      ```
      curl -X POST -H "Content-type: application/json"  -d '{"query": "新宿"}'  http://localhost:5000
      ```
    - 出力
      ```
      127.0.0.1 - - [25/May/2022 10:07:01] "POST / HTTP/1.1" 200 -
      ```
- case2
    - 入力
      ```
      curl -X POST -H "Content-type: application/json"  -d '{"query": ""}'  http://localhost:5000
      ```
    - 出力
      ```
      127.0.0.1 - - [25/May/2022 10:06:52] "POST / HTTP/1.1" 404 -
      ```

2022-06-01 00:53 UTC, taisei-watanabe requested changes
よろしくおねがいします！

2022-06-01 00:53 UTC, taisei-watanabe commented on app.py
> +        return not_found(latlng)
404 not found エラーのガード節にしてしまいましょう。

```py
if status == 404:
    return not_found(latlng)

return make_response(jsonify(latlng))
```

2022-06-01 00:53 UTC, taisei-watanabe commented on src/smart_sauna_map/geocoding.py
> +    return {"lat": None, "lng": None}, 404
こちらも 404 not found error のガード節にしてしまいましょう。
```py
if not location:
    return {"lat": None, "lng": None}, 404

return {"lat": location.latitude, "lng": location.longitude}, 200
```

2022-06-01 00:53 UTC, taisei-watanabe commented on tests/test_get_latlng.py
> +class TestGetLagLng:
テストの結果が Google API server の状態に依存してしまっているので、以下のどちらかで対処すると依存を回避することができます。:thumbsup:

1. Google API server のモックサーバーを立てる
1. `mocker.patch` などを使って返り値をモックする [参考](https://zenn.dev/re24_1986/articles/0a7895b1429bfa#%E6%88%BB%E3%82%8A%E5%80%A4%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%99%E3%82%8B)

2022-06-02 00:33 UTC, taisei-watanabe commented on src/smart_sauna_map/geocoding.py
> +    return {"lat": None, "lng": None}, 404
abort を使ってエラーを送出するようにする
https://msiz07-flask-docs-ja.readthedocs.io/ja/latest/errorhandling.html#returning-api-errors-as-json

2022-06-06 22:32 UTC, siida36 commented on src/smart_sauna_map/get_latlng.py
> +    if len(res_dict["results"]) != 1:
対応しました m(_ _)m bbdd016

2022-06-06 22:39 UTC, siida36 commented
↓こちらのコミットがなぜか行方不明になっていたので、コミットメッセージ通りの修正ができていることを確認した上で forced push しました。
[Fix to use @app.errorhandler](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/7607381127dded0a888ead4b355dfdc71cdb4c68) [7607381](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/7607381127dded0a888ead4b355dfdc71cdb4c68)

2022-06-06 22:41 UTC, siida36 commented on src/smart_sauna_map/get_latlng.py
> +    if len(res_dict["results"]) != 1:
こちらで対応済みです [bbdd016](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/bbdd01671b03140f0d120976f7aad364eaa461c0)

2022-06-06 22:41 UTC, siida36 commented on app.py
> +        return not_found(latlng)
これガード節っていうのか。ありがとうございます！
こちらで対応しました。[297d6f6](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/297d6f6af119c1719ad7908381eaaddf932b745e)

2022-06-06 22:41 UTC, siida36 commented on src/smart_sauna_map/geocoding.py
> +    return {"lat": None, "lng": None}, 404
ガード節、 abort ともにこちらで対応しました。[297d6f6](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/297d6f6af119c1719ad7908381eaaddf932b745e)

2022-06-06 23:02 UTC, siida36 commented on tests/test_get_latlng.py
> +class TestGetLagLng:
ありがとうございます！ `mocker.patch` 使ってみました [7861483](https://github.com/asaka2-alb/smart-sauna-map-back/pull/7/commits/78614832f8362931b7435393096bbcfd321f3424)

2022-06-06 23:03 UTC, siida36 commented
いただいた指摘ぜんぶ対応しました！再レビューお願いします m(_ _)m

2022-06-07 00:29 UTC, taisei-watanabe approved these changes
ありがとうございます！

2022-06-07 00:43 UTC, merged