Feature/#8 fix duplication
asaka2-alb/smart-sauna-map-back pull request #9
Opened 2022-06-08 01:00 UTC by siida36

2022-06-15 01:17 UTC, siida36 commented
TODO: mocker を使って integration test を書き直す

2022-07-11 01:10 UTC, taisei-watanabe requested changes
よろしくおねがいします！

2022-07-11 01:10 UTC, taisei-watanabe commented on src/smart_sauna_map/api.py
> +@app.errorhandler(404)
gecoding.py の `raise NotFound` が走ったときに、この関数が呼ばれることを明示するためにデコレータの中身を書き換えてみました。

```py
@app.errorhandler(NotFound)
def handle_bad_request(e):
    return e, 404
```

2022-07-11 01:10 UTC, taisei-watanabe commented on src/smart_sauna_map/api.py
> +    # response.headers.add("Access-Control-Allow-Origin", "*")
細かいですが、この行は削除してもよいですかね。

2022-07-11 01:10 UTC, taisei-watanabe commented on src/smart_sauna_map/geocoding.py
> +def geocode(query: str, *, timeout: float = 30.0) -> dict[str, float | None]:
エラーの意味が明確になるように、以下のようにしてはどうでしょう。

```py
from werkzeug.exceptions import NotFound

load_dotenv(dotenv_path=join(dirname(__file__), ".env"))

GOOGLE_MAP_API_KEY = os.environ.get("GOOGLE_MAP_API_KEY")


def geocode(
    query: str, *, timeout: float = 30.0
) -> tuple[dict[str, float | None], int]:
    try:
        location = geopy.geocoders.GoogleV3(
            api_key=GOOGLE_MAP_API_KEY, domain="maps.google.co.jp", timeout=timeout
        ).geocode(query)

    except geopy.exc.GeocoderQueryError:
        raise NotFound("Sauna not found.")

    if not location:
        raise NotFound("Sauna not found.")

    return {"lat": location.latitude, "lng": location.longitude}, 200
```

2022-07-11 01:10 UTC, taisei-watanabe commented on tests/integration/test_geocoding.py
> +@pytest.mark.parametrize(
`test_normal` と `test_abnormal` を以下に変えてみてはいかがでしょう。

```py
@pytest.mark.parametrize(
    "input, expected",
    [
        (
            "新宿",
            {"status_code": 200, "response": {"lat": 35.6938253, "lng": 139.7033559}},
        )
    ],
)
def test_when_receive_200_response(mocker, input, expected):
    mocker.patch(
        "smart_sauna_map.geocoding.geocode",
        return_value=({"lat": 35.6938253, "lng": 139.7033559}, 200),
    )
    response = app.test_client().post("/", json={"query": input})

    assert response.status_code == expected["status_code"]
    assert response.get_json() == expected["response"]


@pytest.mark.parametrize(
    "input, expected",
    [("", {"status_code": 404, "response": None})],
)
def test_when_receive_404_response(mocker, input, expected):
    mocker.patch(
        "smart_sauna_map.geocoding.geocode",
        return_value=({"lat": None, "lng": None}, 404),
    )
    response = app.test_client().post("/", json={"query": input})

    assert response.status_code == expected["status_code"]
    assert response.get_json() == expected["response"]

```

2022-08-03 00:32 UTC, taisei-watanabe commented on src/smart_sauna_map/api.py
> +@app.errorhandler(404)
自分で言っておいて申し訳ないですけど
Flask で依存するなら、以下の書き方で統一した方が良いかもしれませんね。

```
app.route('/abort/notfound')
def abort_notfound():
    abort(404)
```

2022-08-23 00:58 UTC, merged